knife4j:
  production: false

logging:
  file:
    path: ./logs

spring:
  data:
    redis:
      database: 0
      host: 127.0.0.1
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          max-wait: -1ms
          min-idle: 0
      password: ''
      port: 6379
      timeout: 10s
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    url: jdbc:mysql://localhost:3306/gemini?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
